version: '3.4'

services:
  audiencesapi:
     image: ${DOCKER_REGISTRY-}audiencesapi
     build: 
       context: .
       dockerfile: Microservices/Audiences/Audiences.Api/Dockerfile
     ports:
       - 7001:80
  corpusesapi:
     image: ${DOCKER_REGISTRY-}corpusesapi
     build: 
       context: .
       dockerfile: Microservices/Corpuses/Corpuses.Api/Dockerfile
     ports:
       - 7002:80
  apigateway:
     image: ${DOCKER_REGISTRY-}universityfundaccountingapigateway
     build:
       context: .
       dockerfile: UniversityFundAccounting.ApiGateway/Dockerfile
     ports:
        - 5000:80
     links:
       - audiencesapi
       - corpusesapi
     depends_on:
       - audiencesapi
       - corpusesapi
    

